---
# tasks file for installRancher
- name: Install the package "python3-pip"
  apt:
    name: python3-pip
    state: present

- name: install dependencies
  pip:
    name: docker-py

- name: Create a Rancher container
  docker_container:
    name: Rancher
    image: rancher/server
    restart_policy: unless-stopped
    ports: "8080:8080"
    state: started
