---
# tasks file for installDocker
- name: Install prerequirements packages apt-transport-https
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add apt-key for docker
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add sources
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install the package "docker-ce"
  apt:
    name: docker-ce
    state: present
